### PR TITLE
Implement models for PIXV3 and PDQV3 Queries

### PR DESCRIPTION
**Pull request by qligier**
This PR adds models for ITI-45 (PIX V3 Query) and ITI-47 (PDQ V3 Query) transactions.

- PIX V3 Query: raw models (PRPAIN201309UV02Type and PRPAIN201310UV02Type) and simplified models (PixV3QueryQuery and PixV3QueryResponse); the simplified response model offers a quick initialization method: `PixV3QueryResponse.fromQuery(pixV3QueryQuery)`.
- PDQ V3 Query: raw models without continuation support (PRPAIN201305UV02Type and PRPAIN201306UV02Type).

It introduces _net.ihe.gazelle:hl7v3-code-jar_ as a new dependency from the Gazelle repository (https://gazelle.ihe.net/nexus/content/groups/public/). Is it ok?
The class HL7DTM has been moved from _ipf-commons-ihe-xds_ to _ipf-commons-ihe-core_ to be also usable in _ipf-commons-ihe-hl7v3_.

The library also contains models for the continuation support in PDQ V3 Query (QUQIIN000003UV01Type, QUQIIN000003UV01CancelType and MCCIIN000002UV01Type), and due to the low complexity of these messages, simplified models should be quite easy to implement. That could be the scope of a future work.

To do:

- [ ] Update the documentation to add these models (after merge).

### CODE REVIEW

**Comment by unixoid** [comment]
According to https://gforge.inria.fr/projects/gazelle/, Gazelle code licence is Apache --> OK to use it

**Comment by unixoid** [comment]
Hello @qligier 

I merged your pull request to the branch https://github.com/oehf/ipf/tree/qligier-feature-pixpdqv3 and made some changes (last commit from me — its description references #353 by mistake). Please review the changes and let me know whether they are Ok for you. Are you going to add model classes for ITI-47?

Thank you and best regards
Dmytro

**Comment by unixoid** [comment]
Concurring logging frameworks led to a problem in Iti55Service: The variable mdcContextMap became null, and the statement "MDC.setContextMap(mdcContextMap)" produced an NPE -- what an unexpected dependency ;-)

**Comment by qligier** [comment]
Quite an unexpected consequence indeed, nice catch.
The changes seems good for me, thanks!
About ITI-47, the request and response seem so complex I'm not sure it's worth/possible creating generic simplified models. Instead, I was thinking about creating specific query models (e.g. QueryByDemographics [first and last name, gender, birthdate], QueryByAHV, etc.) in the eHealthConnector. I guess a simplified response model can also be created, thanks to the Swiss usage restrictions? I guess you've much more experience with ITI-47 than me, what do you think?

**Comment by unixoid** [comment]
To be honest, I am not very impressed by the Gazelle HL7v3 Library.  It does not provide any advantages compared to a JAXB stub --- or am I wrong?  Having different, but semantically equivalent classes for the same objects like Device, Sender, or Receiver is very inconvenient and leads to code duplication --- I mean methods `(to|from)(Sender|Receiver)` in the transformers.  Therefore I will most probably continue to use Groovy XML builder/slurper for processind HL7v3 :-)

**Comment by unixoid** [comment]
...and, as there are no pre-defined combinations of query parameters for PDQ (as opposed e.g. to XDS), I cannot make any statement about whether it would make sense to create a set of classes for them in IPF.  Swiss EPR constraints ITI-45 requests, but does not constraint ITI-47 requests (yet).

**Comment by unixoid** [comment]
So, the code is merged to `master` now :)

**Comment by qligier** [comment]
> To be honest, I am not very impressed by the Gazelle HL7v3 Library. It does not provide any advantages compared to a JAXB stub --- or am I wrong?

It _is_ a JAXB stub, so I'm not sure what you mean here.
The library does what I want: it's quite clean (nicely organized in packages), there's constructors with parameters (really useful when dealing with base types) and it allows to have only one implementation of the base types that are used in many different places (PIXv3, PDQv3 but also CDAs and some other places too). Maintaining only one good implementation of these is beneficial.
Are you saying you would prefer to have a simple JAXB stub in IPF instead of this dependency? I've tried to generate with JAXB/XJC the CDA-CH-EMED and PIXv3 models, and it was a complete mess. I don't mind replacing the library with something better suited, but I'm currently unable to do better. Maybe we could import the classes used from the dependency to IPF?

> Having different, but semantically equivalent classes for the same objects like Device, Sender, or Receiver is very inconvenient and leads to code duplication --- I mean methods (to|from)(Sender|Receiver) in the transformers.

Yeah, I don't quite like it either, but they're different types in the library, so how would the converter know which one to create? The only solution I see is to merge _MCCIMT000100UV01Receiver_ and _MCCIMT000100UV01Sender_ in the library.

**Comment by unixoid** [comment]
@qligier: I agree with you and do not propose to replace the library with something else.

**Comment by unixoid** [comment]
IPF documentation (ipf-docs project) is adapted to mention the newly introduced model classes.

**Comment by qligier** [comment]
Sorry for the doc, I started to write it but then holidays happened :sweat_smile:

**Pull request merged**
