### PR TITLE
Enhance atna log events to RAD-69 and RAD-75.

### PR DESCRIPTION
**Pull request by EugenFischer**
According the spec (IHE_RAD_TF_Vol3), on Retrieve Imaging Document Set [RAD-69] and Cross Gateway Retrieve Imaging Document Set [RAD-75] the EventCodeType DICOM Instances Accessed should be used.

### CODE REVIEW

**Comment by unixoid** [comment]
Eugene, thank you for the pull request.  But as you see, unit tests fail.  Could you please try to fix this?

**Comment by ohr** [comment]
Requested to be backported to 3.6 as well

**Comment by EugenFischer** [comment]
Hi Dmytro,
after some discussions and clearer understanding i will prefer to skip this pull request and 
use https://github.com/oehf/ipf/pull/294 instead.

Kind Regards,
Eugen

**Comment by unixoid** [comment]
Dropped in favor of #294.

**Pull request closed without merging**
