### PR TITLE
Implementation of PHARM-5

### PR DESCRIPTION
**Pull request by qligier**
This PR implements the (MHD-based) CMPD [PHARM-5 transaction](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_CMPD.pdf).

- [x] PHARM-5 consumer: working
- [x] PHARM-5 producer: working
- [x] Audit strategy: small issue with the destination in the Document Consumer audit message, the NetworkAccessPoint is missing
- [x] Create tests
- [x] Create documentation [(#5)](https://github.com/oehf/ipf-docs/pull/5)

### CODE REVIEW

**Comment by qligier** [comment]
In ipf-fhir-r4-spring-boot-starter, a `RestfulServerConfiguration` is automatically created if missing but not fully initialized and trying to access /metadata (the capability statement) provokes NPEs because `resourceBindings`, `serverBindings` and `myServerAddressStrategy` are null.
It's an issue because using HAPI's IOperation makes that call (which the IQuery does not seem to). Do IPF expects the user to provide its own RestfulServerConfiguration or should it be fixed in `IpfFhirAutoConfiguration`?

(Weirdly, the IOperation call succeeds even if the ConformanceStatement does not contain that specific operation, so the metadata call seems useless)

**Comment by unixoid** [comment]
@ohr Could you please take a look at @qligier's question?

**Comment by ohr** [comment]
I did already. But I'll add another safety net defending against the
NullPointerException when no resource providers have been registered

Am Di., 29. März 2022 um 15:21 Uhr schrieb Dmytro Rud <
***@***.***>:

**Comment by qligier** [comment]
Thanks @ohr, I've rebased onto your latest changes.

There's a last issue in the audit message that is also present in MHD ITI-67 audit messages: the Document Consumer audit message is missing its destination NetworkAccessPoint (mandatory in the specs):
```xml
<ActiveParticipant UserID="cmpd-pharm5://localhost:8085/fhir?secure=false" UserIsRequestor="false">
	<RoleIDCode codeSystemName="DCM" csd-code="110152" originalText="Destination Role ID"/>
</ActiveParticipant>
```
What should be done about this?

**Comment by ohr** [comment]
Client-side FHIR auditing is very incomplete. It probably needs an IClientInterceptor to be applied by default to FHIR producer endpoints, because the actual URL and Query Parameters are not available yet when the other audit stuff is done. I will have a look at it.

**Comment by qligier** [comment]
Thank you @ohr for the quick patch, it's working well!

### Consumer
```java
public Bundle processPharm5(@Header(value = Constants.FHIR_REQUEST_PARAMETERS) final Pharm5SearchParameters searchParameters) {
    return new Bundle();
}
```

### Producer
```java
final var exchangeSent = new DefaultExchange(camelContext, ExchangePattern.InOut);

// With Pharm5SearchParameters
final var searchParameters = new Pharm5SearchParameters(...);
exchangeSent.getMessage().setHeader(Constants.FHIR_REQUEST_PARAMETERS, searchParameters);

// Or with Parameters
final var parameters = new Parameters();
exchangeSent.getMessage().setBody(parameters);
exchangeSent.getMessage().setHeader(Constants.FHIR_OPERATION_HEADER, Pharm5Operations.FIND_DISPENSES);

final Exchange exchangeReturned = this.producerTemplate.send("cmpd-pharm5://localhost:8085/fhir", exchangeSent);
exchangeReturned.getMessage().getBody(Bundle.class);
```

### Audits
```xml
<!-- Querying actor audit message -->
<AuditMessage>
	<EventIdentification EventActionCode="E" EventDateTime="2022-03-31T12:23:07.234376600Z" EventOutcomeIndicator="0">
		<EventID codeSystemName="DCM" csd-code="110112" originalText="Query"/>
		<EventTypeCode codeSystemName="IHE Transactions" csd-code="PHARM-5" originalText="Query Pharmacy Documents over MHD"/>
	</EventIdentification>
	<ActiveParticipant AlternativeUserID="28024" NetworkAccessPointID="192.168.42.116" NetworkAccessPointTypeCode="2" UserID="UNKNOWN" UserIsRequestor="true">
		<RoleIDCode codeSystemName="DCM" csd-code="110153" originalText="Source Role ID"/>
	</ActiveParticipant>
	<ActiveParticipant NetworkAccessPointID="localhost" NetworkAccessPointTypeCode="1" UserID="http://localhost:8085/fhir/DocumentReference/$find-dispenses" UserIsRequestor="false">
		<RoleIDCode codeSystemName="DCM" csd-code="110152" originalText="Destination Role ID"/>
	</ActiveParticipant>
	<AuditSourceIdentification AuditEnterpriseSiteID="1.2.3" AuditSourceID="ipf-example">
		<AuditSourceTypeCode codeSystemName="DCM" csd-code="4" originalText="Application Server Process or Thread"/>
	</AuditSourceIdentification>
	<ParticipantObjectIdentification ParticipantObjectID="1234^^^&amp;1.2.3&amp;ISO" ParticipantObjectTypeCode="1" ParticipantObjectTypeCodeRole="1">
		<ParticipantObjectIDTypeCode codeSystemName="RFC-3881" csd-code="2" originalText="Patient Number"/>
	</ParticipantObjectIdentification>
	<ParticipantObjectIdentification ParticipantObjectID="$find-dispenses">
		<ParticipantObjectIDTypeCode codeSystemName="IHE Transactions" csd-code="PHARM-5" originalText="Query Pharmacy Documents over MHD"/>
		<ParticipantObjectQuery>cGF0aWVudC5pZGVudGlmaWVyPXVybjpvaWQ6MS4yLjN8MTIzNCZzdGF0dXM9Y3VycmVudA==</ParticipantObjectQuery>
		<ParticipantObjectDetail type="QueryEncoding" value="VVRGLTg="/>
	</ParticipantObjectIdentification>
</AuditMessage>

<!-- Community Pharmacy Manager audit message -->
<AuditMessage>
	<EventIdentification EventActionCode="E" EventDateTime="2022-03-31T12:23:07.207615300Z" EventOutcomeIndicator="0">
		<EventID codeSystemName="DCM" csd-code="110112" originalText="Query"/>
		<EventTypeCode codeSystemName="IHE Transactions" csd-code="PHARM-5" originalText="Query Pharmacy Documents over MHD"/>
	</EventIdentification>
	<ActiveParticipant NetworkAccessPointID="127.0.0.1" NetworkAccessPointTypeCode="2" UserID="/fhir/DocumentReference/$find-dispenses" UserIsRequestor="true">
		<RoleIDCode codeSystemName="DCM" csd-code="110153" originalText="Source Role ID"/>
	</ActiveParticipant>
	<ActiveParticipant AlternativeUserID="28024" NetworkAccessPointID="192.168.42.116" NetworkAccessPointTypeCode="2" UserID="http://localhost:8085/fhir/DocumentReference/$find-dispenses" UserIsRequestor="false">
		<RoleIDCode codeSystemName="DCM" csd-code="110152" originalText="Destination Role ID"/>
	</ActiveParticipant>
	<AuditSourceIdentification AuditEnterpriseSiteID="1.2.3" AuditSourceID="ipf-example">
		<AuditSourceTypeCode codeSystemName="DCM" csd-code="4" originalText="Application Server Process or Thread"/>
	</AuditSourceIdentification>
	<ParticipantObjectIdentification ParticipantObjectID="1234^^^&amp;1.2.3&amp;ISO" ParticipantObjectTypeCode="1" ParticipantObjectTypeCodeRole="1">
		<ParticipantObjectIDTypeCode codeSystemName="RFC-3881" csd-code="2" originalText="Patient Number"/>
	</ParticipantObjectIdentification>
	<ParticipantObjectIdentification ParticipantObjectID="$find-dispenses">
		<ParticipantObjectIDTypeCode codeSystemName="IHE Transactions" csd-code="PHARM-5" originalText="Query Pharmacy Documents over MHD"/>
		<ParticipantObjectQuery>cGF0aWVudC5pZGVudGlmaWVyPXVybjpvaWQ6MS4yLjN8MTIzNCZzdGF0dXM9Y3VycmVudA==</ParticipantObjectQuery>
		<ParticipantObjectDetail type="QueryEncoding" value="VVRGLTg="/>
	</ParticipantObjectIdentification>
</AuditMessage>
```

**Comment by ohr** [comment]
I have actually rearranged this with
commit 7db31c4532f695aa2d89f04eded6cba2e2a1163a. RestfulServerConfiguration
is not an autoconfigured bean anymore. This was also due to an effect that
RestfulServers without any registered FHIR endpoints threw an NPE when the
ConformanceStatement was obtained.

Christian

Am Di., 29. März 2022 um 14:02 Uhr schrieb Quentin Ligier <
***@***.***>:

**Pull request merged**
