### PR TITLE
Read before write

### PR DESCRIPTION
**Pull request by rsteppac**
This PR diff should look exactly the same as the one for the 3.5 branch, with one exception in the unit test where a Mockito import is different due to the Mockito version upgrade in master.

The question is whether this PR diff should look exactly the same? Master is not API compatible with the 3.5 branch (should be version 4.0 if semantic versioning is applied) and we thus could clean up the constructors of TLSSyslogSenderImpl? Do you think they need cleaning up?

### CODE REVIEW

**Comment by unixoid** [comment]
My two cents on the IPF API compatibility: the API exposed by IPF is what can be used in Camel route definitions, e.g. URI parameters, DSL extensions, validating processors, etc.  Anything else are "internals".

**Comment by rsteppac** [comment]
@unixoid , the ch-ppq component has been removed in the 3.6 branch, as far as I could see (could not get our project to build with the 3.6-SNAPSHOT for that reason). That's a change even on the Camel level.

**Comment by ohr** [comment]
I already cherry-picked the PR from master to 3.5 branch.

With regard to API compatibility: 
in the past, version changes such as from 3.4 to 3.5 had API incompatibilities (e.g. between 3.4 and 3.5, all the internal ATNA audit stuff changed), although we usually don't remove IHE components unless there is a good reason to. I don't know specifically ch-ppq - I think it was in a very preliminary state (at least spec-wise). 
There is always a migration page, although from time to time there might be something missing.

Patch versions (3.5.2 to 3.5.3) should never break existing code.

I thought of 4.0, amongst other things, to get JDK 11 support (or even requiring it) while keeping the 3.x code line maintained for some time.

**Comment by unixoid** [comment]
Yes, the specification of the Swiss national PPQ profile is even now still a draft, and in December 2017 the transaction ch-ppq was split into ch-ppq1 and ch-ppq2.  After the Swiss EPR Projectathon in September 2018, where the new ch-ppq1 and ch-ppq2 were tested, there was no reason anymore to keep supporting the obsolete ch-ppq component in the not-yet-released IPF 3.6.  But IPF 3.5 still supports it.

**Comment by ohr** [comment]
yes, you can delete it

**Pull request closed without merging**
